services:
  - type: web
    name: metadata-changer
    env: python
    plan: starter
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
